env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
plugins:
  - html
  - template
parserOptions:
  ecmaVersion: latest
ignorePatterns: ["**/vendor/*.js", "**/staticfiles/**"]
rules: {}
