[tool.black]
line-length = 88
extend-exclude = "migrations"

[tool.pylint.master]
ignore = "migrations"
recursive = "yes"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"
