[tool.black]
line-length = 88
extend-exclude = "migrations"

[tool.pylint.master]
ignore = "migrations"
recursive = "yes"
load-plugins = "pylint_django"
django-settings-module = "cms.settings"
jobs = 0

[tool.pylint.messages_control]
disable = [
    "C0326", "C0330", # Recommended by Black
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "imported-auth-user"
]
max-parents = 10
good-names = ["i","j","k","ex","Run","_","id","pk"]

[tool.pylint.format]
max-line-length = 88
