# This file may be used to create an environment using:
# $ conda env create -f <this file>
name: geo
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - asgiref=3.3.1
  - autopep8=1.5.5
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - django=3.1.6
  - django-filter=2.4.0
  - libffi=3.3
  - openssl=1.1.1j
  - pip=21.0.1
  - pycodestyle=2.6.0
  - python=3.8.6
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - setuptools=49.6.0
  - sqlite=3.34.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - toml=0.10.2
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
