# Generated by Django 4.0.3 on 2022-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='lon',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
