# Generated by Django 3.1.4 on 2020-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='cct_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='remoteness_index',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='student_classroom_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='student_teacher_ratio',
            field=models.FloatField(),
        ),
    ]
