# Generated by Django 4.0.3 on 2022-04-05 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_school_lat_alter_school_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='lon',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
