# Generated by Django 3.1.4 on 2020-12-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20201214_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alldata',
            new_name='School',
        ),
    ]
