# Generated by Django 3.1.4 on 2020-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20201215_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(unique=True),
        ),
    ]
