# Generated by Django 4.0.3 on 2022-04-07 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_school_data_year_alter_school_gender_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.TextField()),
                ('country', models.TextField()),
                ('school_name', models.TextField()),
                ('sector', models.TextField(blank=True)),
                ('school_level', models.TextField(blank=True)),
                ('municipality', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('zone', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
            ],
            options={
                'db_table': 'schoolv2',
            },
        ),
        migrations.CreateModel(
            name='SchoolV2Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(blank=True)),
                ('data_year', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('total_enrollment', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('test_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gender_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.schoolv2')),
            ],
            options={
                'db_table': 'schoolv2session',
            },
        ),
    ]
