# Generated by Django 4.0.3 on 2022-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_schoolv2_schoolv2session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolv2session',
            name='gender_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolv2session',
            name='test_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolv2session',
            name='total_enrollment',
            field=models.IntegerField(null=True),
        ),
    ]
