# Generated by Django 4.0.3 on 2022-04-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_schoolv2_lat_alter_schoolv2_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolv2session',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school_app.schoolv2'),
        ),
    ]
