# Generated by Django 3.1.7 on 2021-04-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'managed': False},
        ),
    ]
