# Generated by Django 4.0.3 on 2022-04-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_alter_schoolv2session_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'school (old)', 'verbose_name_plural': 'schools (old)'},
        ),
        migrations.AlterModelOptions(
            name='schoolv2',
            options={'verbose_name': 'school'},
        ),
        migrations.AlterModelOptions(
            name='schoolv2session',
            options={'verbose_name': 'school session'},
        ),
    ]
