# Generated by Django 3.2 on 2021-04-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20210420_1754'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
    ]
