# Generated by Django 4.0.3 on 2022-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_alter_school_options_alter_schoolv2_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolv2',
            constraint=models.UniqueConstraint(fields=('country', 'school_id'), name='country_unique_id'),
        ),
        migrations.AddConstraint(
            model_name='schoolv2session',
            constraint=models.UniqueConstraint(fields=('school', 'data_year', 'session'), name='school_unique_year_session'),
        ),
    ]
