# Generated by Django 4.0.3 on 2022-04-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_alter_school_options_alter_schoolv2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolv2',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolv2',
            name='school_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolv2session',
            name='session',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='schoolv2',
            index=models.Index(fields=['country', 'school_id'], name='school_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolv2session',
            index=models.Index(fields=['school', 'data_year'], name='session_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolv2',
            constraint=models.UniqueConstraint(fields=('country', 'school_id'), name='country_unique_id'),
        ),
        migrations.AddConstraint(
            model_name='schoolv2session',
            constraint=models.UniqueConstraint(fields=('school', 'data_year', 'session'), name='school_unique_year_session'),
        ),
    ]
