# Generated by Django 2.1 on 2019-12-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alldata',
            fields=[
                ('school_year', models.TextField(blank=True, null=True)),
                ('school_id', models.TextField(blank=True, null=True)),
                ('cluster', models.TextField(blank=True, null=True)),
                ('remoteness_index', models.TextField(blank=True, null=True)),
                ('total_recieving_cct', models.TextField(blank=True, null=True)),
                ('cct_percentage', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('original_water_boolean', models.TextField(blank=True, null=True)),
                ('nowater', models.TextField(blank=True, null=True)),
                ('original_internet_boolean', models.TextField(blank=True, null=True)),
                ('no_internet', models.TextField(blank=True, null=True)),
                ('noelec', models.TextField(blank=True, null=True)),
                ('original_electricity_boolean', models.TextField(blank=True, null=True)),
                ('instructional_rooms', models.TextField(blank=True, null=True)),
                ('student_classroom_ratio', models.TextField(blank=True, null=True)),
                ('total_teachers', models.TextField(blank=True, null=True)),
                ('student_teacher_ratio', models.TextField(blank=True, null=True)),
                ('accessibility', models.TextField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('shi_score', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('school_name', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('municipality', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('total_female', models.TextField(blank=True, null=True)),
                ('total_male', models.TextField(blank=True, null=True)),
                ('total_enrollment', models.TextField(blank=True, null=True)),
                ('ds_total', models.TextField(blank=True, null=True)),
                ('cp_total', models.TextField(blank=True, null=True)),
                ('dcm_total', models.TextField(blank=True, null=True)),
                ('drcpau_total', models.TextField(blank=True, null=True)),
                ('dh_total', models.TextField(blank=True, null=True)),
                ('autism_total', models.TextField(blank=True, null=True)),
                ('wcg_total', models.TextField(blank=True, null=True)),
                ('eb_total', models.TextField(blank=True, null=True)),
                ('hi_total', models.TextField(blank=True, null=True)),
                ('id_total', models.TextField(blank=True, null=True)),
                ('li_total', models.TextField(blank=True, null=True)),
                ('md_total', models.TextField(blank=True, null=True)),
                ('pd_total', models.TextField(blank=True, null=True)),
                ('shp_total', models.TextField(blank=True, null=True)),
                ('speech_total', models.TextField(blank=True, null=True)),
                ('vi_total', models.TextField(blank=True, null=True)),
                ('ii_total', models.TextField(blank=True, null=True)),
                ('p_total', models.TextField(blank=True, null=True)),
                ('pwd_total', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AllData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
