# Generated by Django 3.1.7 on 2021-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_auto_20201215_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
