name: lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx eslint --ext .js,.html .
      - run: npx prettier -c .
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - run: pylint cms
      - run: black .
